name: babyai
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.6
    - pytorch=1.4
    - numpy
    - blosc
    - pip
    - pip:
        - scikit-build
        - torch
        - opencv-python
        - gym_minigrid
        - numpy==1.19.5
        - gym=0.18.0
        - colorama
        - matplotlib==2.2.3
        - imageio==2.4.1
        - joblib==0.12.4
