version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: pip3 install --user --process-dependency-links --editable .
      - run: pip3 install --user flake8
      - run: python3 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823
      - run: ./run_tests.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
