version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: pip3 install --user --process-dependency-links --editable .
      - run: ./run_tests.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
